# Workflow funcionando
name: CI/CD Pipeline - Teste e Deploy

# Define quando o workflow deve rodar
on:
  # Dispara a pipeline em todo 'push' para a branch 'principal'
  push:
    branches: [ principal ] 
  workflow_dispatch:

# Define os trabalhos que a pipeline executará
jobs:
  build-e-testar:
    # Define o ambiente onde o job rodará
    runs-on: windows-latest

    steps:
      # 1. Baixa o código do repositório para o servidor
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instala as dependências do projeto
      - name: Instalar dependências
        run: npm install

      # 4. Roda os testes 
      - name: Rodar os testes
        run: npm run test

      # 5. Disparar Deploy no Render 
      - name: Disparar Deploy no Render
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

